set syntax=on
set number
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set nowrap
set noswapfile
set nobackup
set undofile
set smartcase
set ignorecase
set incsearch
set mouse="a"
set clipboard="unnamedplus"
set splitbelow
set splitright
set scrolloff=6
set sidescrolloff=15
set pumheight=10
set nohlsearch
set rnu
