require("config.sets")
require("config.keymap")
require("config.lsp")
require("config.lualine")
require("config.treesitter")
require("config.plugins")
require("config.autopairs")
require("config.comments")
