
[font]
normal = { family = "NotoSansM Nerd Font", style = "Regular" }
size = 14

[window]
opacity = 0.9
startup_mode = "Maximized"

[general]
import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]
